[build]
command = "react-router build"
publish = "build/client"

[dev]
command = "react-router dev"

# Static assets - long-term caching
[[headers]]
  for = "/img/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# HTML and dynamic content - CDN caching with stale-while-revalidate
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Netlify-CDN-Cache-Control = "public, s-maxage=300, stale-while-revalidate=604800"
